version: '3'

volumes:
  pg_data:
  static:
  certs:
  nginx_conf:

services:
  website:
    restart: always
    build: ./tokenswave/
    env_file: .env
    volumes:
      - static:/app/staticfiles  # Статика собирается в директорию '/app/staticfiles'

  gateway:
    depends_on:
      - website
    build: ./nginx/
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static:/static  # Nginx использует директорию '/static' для статики
      - certs:/etc/letsencrypt
      - nginx_conf:/etc/nginx/templates